<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Illuminate\Support\Facades\Hash;

class GuruSeeder extends Seeder
{
    /**
     * Run the database seeds.
     * Data Guru untuk Madrasah Aliyah dengan fokus Kitab dan Tahfidz
     */
    public function run(): void
    {
        $data = [
            // Pimpinan
            [
                'username' => 'kh.ahmad.fauzi',
                'password' => Hash::make('guru123'),
                'nama' => 'KH. Ahmad Fauzi, Lc., M.Pd.I.',
                'nip' => '197501152000011001',
                'sk' => 'SK/001/MA/2000',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '1975-01-15',
                'alamat' => 'Jl. Pesantren No. 1, Kel. Sukamaju',
                'pendidikan' => 'S2 Pendidikan Islam - UIN Sunan Kalijaga',
                'kontak' => '081234567890',
                'email' => 'kh.ahmad@ma-aliyah.sch.id',
                'tmt' => '2000-01-01',
                'jabatan' => 'Kepala Madrasah',
                'status' => 'Aktif',
            ],
            [
                'username' => 'ust.muhammad.ridwan',
                'password' => Hash::make('guru123'),
                'nama' => 'Ust. Muhammad Ridwan, S.Pd.I., M.Ag.',
                'nip' => '198003202005011002',
                'sk' => 'SK/002/MA/2005',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Tasikmalaya',
                'tanggal_lahir' => '1980-03-20',
                'alamat' => 'Jl. Masjid No. 5, Kel. Cihaur',
                'pendidikan' => 'S2 Ilmu Agama Islam - UIN Bandung',
                'kontak' => '082345678901',
                'email' => 'ust.ridwan@ma-aliyah.sch.id',
                'tmt' => '2005-01-01',
                'jabatan' => 'Wakil Kepala Kurikulum',
                'status' => 'Aktif',
            ],
            [
                'username' => 'ust.abdullah.hakim',
                'password' => Hash::make('guru123'),
                'nama' => 'Ust. Abdullah Hakim, S.Pd.I.',
                'nip' => '198208152008011003',
                'sk' => 'SK/003/MA/2008',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Garut',
                'tanggal_lahir' => '1982-08-15',
                'alamat' => 'Jl. Pondok No. 12, Kel. Jayaraga',
                'pendidikan' => 'S1 Pendidikan Agama Islam - UIN Bandung',
                'kontak' => '083456789012',
                'email' => 'ust.abdullah@ma-aliyah.sch.id',
                'tmt' => '2008-01-01',
                'jabatan' => 'Wakil Kepala Kesiswaan',
                'status' => 'Aktif',
            ],

            // Guru Tahfidz & Al-Quran
            [
                'username' => 'ust.hafidz.rahman',
                'password' => Hash::make('guru123'),
                'nama' => 'Ust. Hafidz Rahman, Lc.',
                'nip' => '198505102010011004',
                'sk' => 'SK/004/MA/2010',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Sukabumi',
                'tanggal_lahir' => '1985-05-10',
                'alamat' => 'Jl. Tahfidz No. 7, Kel. Citamiang',
                'pendidikan' => 'S1 Ilmu Al-Quran - Al-Azhar Kairo',
                'kontak' => '084567890123',
                'email' => 'ust.hafidz@ma-aliyah.sch.id',
                'tmt' => '2010-01-01',
                'jabatan' => 'Koordinator Tahfidz / Guru Tahfidz',
                'status' => 'Aktif',
            ],
            [
                'username' => 'usth.siti.aisyah',
                'password' => Hash::make('guru123'),
                'nama' => 'Usth. Siti Aisyah, S.Pd.I.',
                'nip' => '199001152015012005',
                'sk' => 'SK/005/MA/2015',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1990-01-15',
                'alamat' => 'Jl. Quran No. 3, Kel. Cibiru',
                'pendidikan' => 'S1 Ilmu Al-Quran dan Tafsir - UIN Bandung',
                'kontak' => '085678901234',
                'email' => 'usth.aisyah@ma-aliyah.sch.id',
                'tmt' => '2015-01-01',
                'jabatan' => 'Guru Tahfidz & Al-Quran Hadits',
                'status' => 'Aktif',
            ],
            [
                'username' => 'ust.yusuf.mansur',
                'password' => Hash::make('guru123'),
                'nama' => 'Ust. Yusuf Mansur, S.Q.',
                'nip' => '198807202012011006',
                'sk' => 'SK/006/MA/2012',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Bogor',
                'tanggal_lahir' => '1988-07-20',
                'alamat' => 'Jl. Hafalan No. 9, Kel. Cisarua',
                'pendidikan' => 'S1 Ilmu Al-Quran - PTIQ Jakarta',
                'kontak' => '086789012345',
                'email' => 'ust.yusuf@ma-aliyah.sch.id',
                'tmt' => '2012-01-01',
                'jabatan' => 'Guru Tahfidz & Seni Baca Al-Quran',
                'status' => 'Aktif',
            ],

            // Guru Kitab Kuning
            [
                'username' => 'kh.umar.said',
                'password' => Hash::make('guru123'),
                'nama' => 'KH. Umar Said, Lc., M.H.I.',
                'nip' => '197012102002011007',
                'sk' => 'SK/007/MA/2002',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Cirebon',
                'tanggal_lahir' => '1970-12-10',
                'alamat' => 'Jl. Kitab No. 15, Kel. Kejaksan',
                'pendidikan' => 'S2 Hukum Islam - UIN Jakarta',
                'kontak' => '087890123456',
                'email' => 'kh.umar@ma-aliyah.sch.id',
                'tmt' => '2002-01-01',
                'jabatan' => 'Guru Kitab Fiqih & Nahwu Shorof',
                'status' => 'Aktif',
            ],
            [
                'username' => 'ust.ibrahim.nawawi',
                'password' => Hash::make('guru123'),
                'nama' => 'Ust. Ibrahim Nawawi, Lc.',
                'nip' => '198304252011011008',
                'sk' => 'SK/008/MA/2011',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Indramayu',
                'tanggal_lahir' => '1983-04-25',
                'alamat' => 'Jl. Tafsir No. 8, Kel. Sindang',
                'pendidikan' => 'S1 Tafsir Hadits - Al-Azhar Kairo',
                'kontak' => '088901234567',
                'email' => 'ust.ibrahim@ma-aliyah.sch.id',
                'tmt' => '2011-01-01',
                'jabatan' => 'Guru Kitab Tafsir & Hadits',
                'status' => 'Aktif',
            ],
            [
                'username' => 'ust.salim.azhari',
                'password' => Hash::make('guru123'),
                'nama' => 'Ust. Salim Azhari, S.Ag.',
                'nip' => '198609182014011009',
                'sk' => 'SK/009/MA/2014',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Majalengka',
                'tanggal_lahir' => '1986-09-18',
                'alamat' => 'Jl. Tasawuf No. 22, Kel. Cigasong',
                'pendidikan' => 'S1 Tasawuf dan Psikoterapi - UIN Bandung',
                'kontak' => '089012345678',
                'email' => 'ust.salim@ma-aliyah.sch.id',
                'tmt' => '2014-01-01',
                'jabatan' => 'Guru Kitab Tasawuf & Aqidah Akhlak',
                'status' => 'Aktif',
            ],

            // Guru Agama
            [
                'username' => 'ust.zakaria.ahmad',
                'password' => Hash::make('guru123'),
                'nama' => 'Ust. Zakaria Ahmad, S.Pd.I.',
                'nip' => '198711122016011010',
                'sk' => 'SK/010/MA/2016',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Kuningan',
                'tanggal_lahir' => '1987-11-12',
                'alamat' => 'Jl. Fiqih No. 5, Kel. Cigugur',
                'pendidikan' => 'S1 Pendidikan Agama Islam - UIN Bandung',
                'kontak' => '081123456789',
                'email' => 'ust.zakaria@ma-aliyah.sch.id',
                'tmt' => '2016-01-01',
                'jabatan' => 'Guru Fiqih',
                'status' => 'Aktif',
            ],
            [
                'username' => 'usth.fatimah.zahra',
                'password' => Hash::make('guru123'),
                'nama' => 'Usth. Fatimah Zahra, S.Pd.I.',
                'nip' => '199205082018012011',
                'sk' => 'SK/011/MA/2018',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Subang',
                'tanggal_lahir' => '1992-05-08',
                'alamat' => 'Jl. Akhlak No. 11, Kel. Subang',
                'pendidikan' => 'S1 Pendidikan Agama Islam - UPI',
                'kontak' => '082234567890',
                'email' => 'usth.fatimah@ma-aliyah.sch.id',
                'tmt' => '2018-01-01',
                'jabatan' => 'Guru Aqidah Akhlak',
                'status' => 'Aktif',
            ],
            [
                'username' => 'ust.hasan.basri',
                'password' => Hash::make('guru123'),
                'nama' => 'Ust. Hasan Basri, S.Pd.I.',
                'nip' => '198902252017011012',
                'sk' => 'SK/012/MA/2017',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Purwakarta',
                'tanggal_lahir' => '1989-02-25',
                'alamat' => 'Jl. SKI No. 7, Kel. Nagri Kaler',
                'pendidikan' => 'S1 Sejarah Peradaban Islam - UIN Jakarta',
                'kontak' => '083345678901',
                'email' => 'ust.hasan@ma-aliyah.sch.id',
                'tmt' => '2017-01-01',
                'jabatan' => 'Guru SKI',
                'status' => 'Aktif',
            ],

            // Guru Bahasa
            [
                'username' => 'ust.faruq.abdullah',
                'password' => Hash::make('guru123'),
                'nama' => 'Ust. Faruq Abdullah, Lc., M.Pd.',
                'nip' => '198406152009011013',
                'sk' => 'SK/013/MA/2009',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Karawang',
                'tanggal_lahir' => '1984-06-15',
                'alamat' => 'Jl. Arab No. 20, Kel. Klari',
                'pendidikan' => 'S2 Pendidikan Bahasa Arab - UIN Malang',
                'kontak' => '084456789012',
                'email' => 'ust.faruq@ma-aliyah.sch.id',
                'tmt' => '2009-01-01',
                'jabatan' => 'Guru Bahasa Arab',
                'status' => 'Aktif',
            ],
            [
                'username' => 'ibu.sri.wahyuni',
                'password' => Hash::make('guru123'),
                'nama' => 'Sri Wahyuni, S.Pd.',
                'nip' => '199103182019012014',
                'sk' => 'SK/014/MA/2019',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1991-03-18',
                'alamat' => 'Jl. Bahasa No. 15, Kel. Antapani',
                'pendidikan' => 'S1 Pendidikan Bahasa Indonesia - UPI',
                'kontak' => '085567890123',
                'email' => 'sri.wahyuni@ma-aliyah.sch.id',
                'tmt' => '2019-01-01',
                'jabatan' => 'Guru Bahasa Indonesia',
                'status' => 'Aktif',
            ],
            [
                'username' => 'ibu.linda.permata',
                'password' => Hash::make('guru123'),
                'nama' => 'Linda Permata, S.Pd.',
                'nip' => '199307222020012015',
                'sk' => 'SK/015/MA/2020',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Bekasi',
                'tanggal_lahir' => '1993-07-22',
                'alamat' => 'Jl. English No. 8, Kel. Bekasi Timur',
                'pendidikan' => 'S1 Pendidikan Bahasa Inggris - UNJ',
                'kontak' => '086678901234',
                'email' => 'linda.permata@ma-aliyah.sch.id',
                'tmt' => '2020-01-01',
                'jabatan' => 'Guru Bahasa Inggris',
                'status' => 'Aktif',
            ],

            // Guru Umum
            [
                'username' => 'pak.agus.riyanto',
                'password' => Hash::make('guru123'),
                'nama' => 'Agus Riyanto, S.Pd.',
                'nip' => '198808102015011016',
                'sk' => 'SK/016/MA/2015',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Cianjur',
                'tanggal_lahir' => '1988-08-10',
                'alamat' => 'Jl. Matematika No. 3, Kel. Cianjur',
                'pendidikan' => 'S1 Pendidikan Matematika - UPI',
                'kontak' => '087789012345',
                'email' => 'agus.riyanto@ma-aliyah.sch.id',
                'tmt' => '2015-01-01',
                'jabatan' => 'Guru Matematika',
                'status' => 'Aktif',
            ],
            [
                'username' => 'ibu.dewi.sartika',
                'password' => Hash::make('guru123'),
                'nama' => 'Dewi Sartika, S.Pd.',
                'nip' => '199004152018012017',
                'sk' => 'SK/017/MA/2018',
                'jenis_kelamin' => 'P',
                'tempat_lahir' => 'Sumedang',
                'tanggal_lahir' => '1990-04-15',
                'alamat' => 'Jl. IPA No. 12, Kel. Sumedang',
                'pendidikan' => 'S1 Pendidikan IPA - UPI',
                'kontak' => '088890123456',
                'email' => 'dewi.sartika@ma-aliyah.sch.id',
                'tmt' => '2018-01-01',
                'jabatan' => 'Guru IPA',
                'status' => 'Aktif',
            ],
            [
                'username' => 'pak.dedi.mulyadi',
                'password' => Hash::make('guru123'),
                'nama' => 'Dedi Mulyadi, S.Pd.',
                'nip' => '198712202016011018',
                'sk' => 'SK/018/MA/2016',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Bandung',
                'tanggal_lahir' => '1987-12-20',
                'alamat' => 'Jl. IPS No. 6, Kel. Ujungberung',
                'pendidikan' => 'S1 Pendidikan IPS - UPI',
                'kontak' => '089901234567',
                'email' => 'dedi.mulyadi@ma-aliyah.sch.id',
                'tmt' => '2016-01-01',
                'jabatan' => 'Guru IPS',
                'status' => 'Aktif',
            ],
            [
                'username' => 'pak.bambang.sutrisno',
                'password' => Hash::make('guru123'),
                'nama' => 'Bambang Sutrisno, S.Pd.',
                'nip' => '198501052013011019',
                'sk' => 'SK/019/MA/2013',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Depok',
                'tanggal_lahir' => '1985-01-05',
                'alamat' => 'Jl. PKn No. 4, Kel. Depok',
                'pendidikan' => 'S1 Pendidikan PKn - UPI',
                'kontak' => '081012345678',
                'email' => 'bambang.sutrisno@ma-aliyah.sch.id',
                'tmt' => '2013-01-01',
                'jabatan' => 'Guru PKn',
                'status' => 'Aktif',
            ],

            // Guru Keterampilan
            [
                'username' => 'ust.ahmad.khatib',
                'password' => Hash::make('guru123'),
                'nama' => 'Ust. Ahmad Khatib, S.Sn.',
                'nip' => '199106152021011020',
                'sk' => 'SK/020/MA/2021',
                'jenis_kelamin' => 'L',
                'tempat_lahir' => 'Jakarta',
                'tanggal_lahir' => '1991-06-15',
                'alamat' => 'Jl. Kaligrafi No. 2, Kel. Tanah Abang',
                'pendidikan' => 'S1 Seni Kaligrafi Islam - ISI Surakarta',
                'kontak' => '082123456789',
                'email' => 'ust.khatib@ma-aliyah.sch.id',
                'tmt' => '2021-01-01',
                'jabatan' => 'Guru Khot/Kaligrafi',
                'status' => 'Aktif',
            ],
        ];

        foreach ($data as $item) {
            DB::table('guru')->insert(array_merge($item, [
                'created_at' => now(),
                'updated_at' => now(),
            ]));
        }
    }
}
